### ISSUE TITLE
Newest version fails with most recent Bitbcuket server

### ISSUE THREAD

**Issue by henriklynggaard** [OrbitzWorldwide/stash-permission-viewer-plugin#5]
I have just upgraded stash 3.9.2 to bitbucket server 4.1.3 and updated the plugin to version 1.3

Whenever I click view permissions I get s 500 internal error and the log below stacktrace..

I have tried disabling and re-enabling the plugin. I can see that manage plugins reports "13 of 13 modules enabled" including "Soy Templates(soy-templates)"

2015-11-30 12:26:50,241 ERROR [http-nio-7990-exec-5] hlh005 @RICQ86x746x11479x0 1j6pi5p 10.3.74.31,127.0.0.1 "GET /plugins/servlet/repositorypermissions/1 HTTP/1.1" c.a.p.s.ServletModuleContainerServlet com.atlassian.soy.renderer.SoyExcep
tion: Unable to compile Soy templates at: com.orbitz.bitbucket.plugins.permission-viewer-plugin:soy-templates
javax.servlet.ServletException: com.atlassian.soy.renderer.SoyException: Unable to compile Soy templates at: com.orbitz.bitbucket.plugins.permission-viewer-plugin:soy-templates
        at com.orbitz.bitbucket.plugins.pvp.servlet.RepositoryPermissionsServlet.render(RepositoryPermissionsServlet.java:113) ~[na:na]
        at com.orbitz.bitbucket.plugins.pvp.servlet.RepositoryPermissionsServlet.doGet(RepositoryPermissionsServlet.java:97) ~[na:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1448853876000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1448853876000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1448853876000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1448853876000.jar:na]
        at com.atlassian.applinks.core.rest.context.ContextFilter.doFilter(ContextFilter.java:26) [applinks-plugin-5.0.1_1448853876000.jar:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.obtainContent(SiteMeshFilter.java:181) [sitemesh-2.5-atlassian-11.jar:na]
        at com.opensymphony.sitemesh.webapp.SiteMeshFilter.doFilter(SiteMeshFilter.java:85) [sitemesh-2.5-atlassian-11.jar:na]
        at com.atlassian.stash.internal.spring.security.StashAuthenticationFilter.doFilter(StashAuthenticationFilter.java:88) [StashAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doInsideSpringSecurityChain(BeforeLoginPluginAuthenticationFilter.java:109) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:75) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.security.auth.trustedapps.filter.TrustedApplicationsFilter.doFilter(TrustedApplicationsFilter.java:94) [atlassian-trusted-apps-core-4.2.0.jar:na]
        at com.atlassian.oauth.serviceprovider.internal.servlet.OAuthFilter.doFilter(OAuthFilter.java:67) [atlassian-oauth-service-provider-plugin-2.0.3_1448836484000.jar:na]
        at com.atlassian.analytics.client.filter.DefaultAnalyticsFilter.doFilter(DefaultAnalyticsFilter.java:36) [analytics-client-4.3.2_1448836482000.jar:na]
        at com.atlassian.analytics.client.filter.AbstractHttpFilter.doFilter(AbstractHttpFilter.java:32) [analytics-client-4.3.2_1448836482000.jar:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doBeforeBeforeLoginFilters(BeforeLoginPluginAuthenticationFilter.java:87) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.web.auth.BeforeLoginPluginAuthenticationFilter.doFilter(BeforeLoginPluginAuthenticationFilter.java:73) [BeforeLoginPluginAuthenticationFilter.class:na]
        at com.atlassian.stash.internal.request.DefaultRequestManager.doAsRequest(DefaultRequestManager.java:85) [bitbucket-service-impl-4.1.3.jar:na]
        at com.atlassian.stash.internal.hazelcast.ConfigurableWebFilter.doFilter(ConfigurableWebFilter.java:38) [ConfigurableWebFilter.class:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]
        ... 201 frames trimmed
Caused by: com.atlassian.soy.renderer.SoyException: Unable to compile Soy templates at: com.orbitz.bitbucket.plugins.permission-viewer-plugin:soy-templates
        at com.atlassian.soy.impl.DefaultSoyManager.render(DefaultSoyManager.java:158) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyTemplateRenderer.render(DefaultSoyTemplateRenderer.java:52) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyTemplateRenderer.render(DefaultSoyTemplateRenderer.java:45) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.doInvoke(ServiceInvoker.java:56) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.internal.aop.ServiceInvoker.invoke(ServiceInvoker.java:60) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invokeUnprivileged(ServiceTCCLInterceptor.java:70) ~[na:na]
        at org.eclipse.gemini.blueprint.service.util.internal.aop.ServiceTCCLInterceptor.invoke(ServiceTCCLInterceptor.java:53) ~[na:na]
        at org.eclipse.gemini.blueprint.service.importer.support.LocalBundleContextAdvice.invoke(LocalBundleContextAdvice.java:57) ~[na:na]
        at com.orbitz.bitbucket.plugins.pvp.servlet.RepositoryPermissionsServlet.render(RepositoryPermissionsServlet.java:104) ~[na:na]
        ... 22 common frames omitted
Caused by: com.google.common.util.concurrent.UncheckedExecutionException: java.lang.IllegalStateException: Required plugin module com.orbitz.bitbucket.plugins.permission-viewer-plugin:soy-templates was either missing or disabled
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2203) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory.get(WebResourceTemplateSetFactory.java:66) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyManager.strainTofu(DefaultSoyManager.java:237) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyManager.access$100(DefaultSoyManager.java:33) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyManager$1.load(DefaultSoyManager.java:70) ~[na:na]
        at com.atlassian.soy.impl.DefaultSoyManager$1.load(DefaultSoyManager.java:66) ~[na:na]
        at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.get(LocalCache.java:3937) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$LocalLoadingCache.getUnchecked(LocalCache.java:4830) ~[guava-18.0.jar:na]
        at com.atlassian.soy.impl.DefaultSoyManager.render(DefaultSoyManager.java:139) ~[na:na]
        ... 30 common frames omitted
Caused by: java.lang.IllegalStateException: Required plugin module com.orbitz.bitbucket.plugins.permission-viewer-plugin:soy-templates was either missing or disabled
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory$TemplateSetBuilder.addTemplatesForTree(WebResourceTemplateSetFactory.java:103) ~[na:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory$TemplateSetBuilder.access$200(WebResourceTemplateSetFactory.java:86) ~[na:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory.findRequiredTemplates(WebResourceTemplateSetFactory.java:80) ~[na:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory.access$000(WebResourceTemplateSetFactory.java:34) ~[na:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory$1.load(WebResourceTemplateSetFactory.java:55) ~[na:na]
        at com.atlassian.soy.impl.WebResourceTemplateSetFactory$1.load(WebResourceTemplateSetFactory.java:51) ~[na:na]
     at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282) ~[guava-18.0.jar:na]
        at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197) ~[guava-18.0.jar:na]

**Comment by boris-yakimov** [comment]
+1 
We have the same issue.

**Comment by NileX13** [comment]
+1 We encountered the same problem.
Was anybody of you able to fix this issue?

**Comment by holsonjr** [comment]
Upgraded to bitbucket 4.4.1 and permissions viewer 1.3 and now have a 500 Oops, an error occurred.  Please see your system administrator.  I called myself and still didn't know what to do.

**Comment by athompso** [comment]
+1 Identical error here on BitBucket 4.1.0 and plugin v1.3.
